export const mainMenuDefault = [
  {
    mainId: 1,
    parentId: 1,
    menuCategory: 'MAIN',
    folderSwitch: 'NO',
    title: '首頁',
    link: 'home',
  },
  {
    mainId: 13,
    parentId: 0,
    menuCategory: 'MAIN',
    folderSwitch: 'NO',
    title: '全站分類',
    link: 'setCategoryView',
    linkData: '0',
    linkDetail: {
      text: '商品分類',
      value: 'setCategoryView',
      data: {
        meta: {
          title: '商品分類',
          url: '',
          urlAndroid: '',
          urlIos: '',
        },
        list: [
          {
            title: 'Ryan',
            url: '/category/1',
            link: 'setCategory',
            linkData: '1',
            sub: [],
          },
          {
            title: '家電',
            url: '/category/2',
            link: 'setCategoryView',
            linkData: '2',
            sub: [
              {
                title: '冰箱',
                url: '/category/21',
                link: 'setCategory',
                linkData: '21',
                sub: [],
              },
              {
                title: '冰櫃/冷凍櫃',
                url: '/category/22',
                link: 'setCategory',
                linkData: '22',
                sub: [],
              },
              {
                title: '冷氣/暖氣',
                url: '/category/23',
                link: 'setCategory',
                linkData: '23',
                sub: [],
              },
              {
                title: '除濕機',
                url: '/category/24',
                link: 'setCategory',
                linkData: '24',
                sub: [],
              },
              {
                title: '掃地機',
                url: '/category/25',
                link: 'setCategory',
                linkData: '25',
                sub: [],
              },
            ],
          },
          {
            title: '3C',
            url: '/category/3',
            link: 'setCategoryView',
            linkData: '3',
            sub: [
              {
                title: '手機/平板',
                url: '/category/31',
                link: 'setCategory',
                linkData: '31',
                sub: [],
              },
              {
                title: '手機/平板配件',
                url: '/category/32',
                link: 'setCategory',
                linkData: '32',
                sub: [],
              },
              {
                title: '相機/相機配件',
                url: '/category/33',
                link: 'setCategory',
                linkData: '33',
                sub: [],
              },
              {
                title: '數位週邊',
                url: '/category/34',
                link: 'setCategory',
                linkData: '34',
                sub: [],
              },
            ],
          },
          {
            title: '休閒服',
            url: '/category/40',
            link: 'setCategoryView',
            linkData: '40',
            sub: [],
          },
          {
            title: '精品',
            url: '/category/49',
            link: 'setCategoryView',
            linkData: '49',
            sub: [],
          },
          {
            title: '休閒服',
            url: '/category/62',
            link: 'setCategoryView',
            linkData: '62',
            sub: [
              {
                title: '歐美品牌',
                url: '/category/63',
                link: 'setCategoryView',
                linkData: '63',
                sub: [
                  {
                    title: 'FILA',
                    url: '/category/67',
                    link: 'setCategory',
                    linkData: '67',
                    sub: [],
                  },
                  {
                    title: 'CK',
                    url: '/category/66',
                    link: 'setCategory',
                    linkData: '66',
                    sub: [],
                  },
                  {
                    title: 'ARMANI EXCHANGE',
                    url: '/category/65',
                    link: 'setCategory',
                    linkData: '65',
                    sub: [],
                  },
                  {
                    title: 'America Eagle',
                    url: '/category/64',
                    link: 'setCategory',
                    linkData: '64',
                    sub: [],
                  },
                ],
              },
              {
                title: '休閒服飾',
                url: '/category/68',
                link: 'setCategoryView',
                linkData: '68',
                sub: [
                  {
                    title: '北歐小刺蝟',
                    url: '/category/70',
                    link: 'setCategory',
                    linkData: '70',
                    sub: [],
                  },
                  {
                    title: 'ONEDER旺達',
                    url: '/category/71',
                    link: 'setCategory',
                    linkData: '69',
                    sub: [],
                  },
                  {
                    title: 'Aaron1982',
                    url: '/category/72',
                    link: 'setCategory',
                    linkData: '71',
                    sub: [],
                  },
                  {
                    title: 'Aaron1982',
                    url: '/category/74',
                    link: 'setCategory',
                    linkData: '71',
                    sub: [],
                  },
                ],
              },
            ],
          },
          {
            title: '書籍類',
            url: '/category/43',
            link: 'setCategoryView',
            linkData: '43',
            sub: [
              {
                title: '文學小說',
                url: '/category/44',
                link: 'setCategoryView',
                linkData: '44',
                sub: [
                  {
                    title: '英國翻譯小說',
                    url: '/category/45',
                    link: 'setCategory',
                    linkData: '45',
                    sub: [],
                  },
                ],
              },
            ],
          },
          {
            title: '廚房系列',
            url: '/category/88',
            link: 'setCategoryView',
            linkData: '88',
            sub: [
              {
                title: '微波爐',
                url: '/category/90',
                link: 'setCategory',
                linkData: '90',
                sub: [],
              },
              {
                title: '氣炸鍋',
                url: '/category/89',
                link: 'setCategory',
                linkData: '89',
                sub: [],
              },
            ],
          },
          {
            title: '生活家具',
            url: '/category/93',
            link: 'setCategoryView',
            linkData: '93',
            sub: [
              {
                title: ' 沙發',
                url: '/category/92',
                link: 'setCategory',
                linkData: '92',
                sub: [],
              },
            ],
          },
          {
            title: '櫃子',
            url: '/category/94',
            link: 'setCategoryView',
            linkData: '94',
            sub: [
              {
                title: '衣櫃/系統櫃',
                url: '/category/95',
                link: 'setCategory',
                linkData: '95',
                sub: [],
              },
            ],
          },
          {
            title: '防疫用品',
            url: '/category/186',
            link: 'setCategoryView',
            linkData: '186',
            sub: [],
          },
          {
            title: '測試第二分類用',
            url: '/category/187',
            link: 'setCategory',
            linkData: '187',
            sub: [],
          },
        ],
      },
    },
    sub: [],
  },
  {
    mainId: 12,
    parentId: 12,
    menuCategory: 'MAIN',
    folderSwitch: 'YES',
    title: '外部連結',
    link: '',
    linkData: '',
    linkDetail: null,
    sub: [
      {
        mainId: 123,
        parentId: 123,
        menuCategory: 'SUB',
        folderSwitch: 'NO',
        title: 'Google',
        link: '_blank',
        linkData: 'https://www.google.com',
        linkDetail: null,
      },
      {
        mainId: 124,
        parentId: 124,
        menuCategory: 'SUB',
        folderSwitch: 'NO',
        title: 'Cakeresume',
        link: '_blank',
        linkData: 'https://www.cakeresume.com/me/yeh-ryan-a061b8',
        linkDetail: null,
      },
      {
        mainId: 125,
        parentId: 125,
        menuCategory: 'SUB',
        folderSwitch: 'NO',
        title: 'Ryan Blog(Medium)',
        link: '_blank',
        linkData: 'https://medium.com/@haix.yeh_54536',
        linkDetail: null,
      },
    ],
  },
  {
    mainId: 11,
    parentId: 11,
    menuCategory: 'MAIN',
    folderSwitch: 'NO',
    title: '最新活動',
    link: 'newEventView',
    linkData: '',
    linkDetail: {
      text: '最新活動',
      value: 'newEventView',
      data: {
        meta: {
          title: '最新活動',
          url: '',
          urlAndroid: '',
          urlIos: '',
        },
        list: [],
      },
    },
    sub: [],
  },
];


export default {
  mainMenuDefault
};